# Generated by Django 4.2.16 on 2024-12-01 02:59

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_options_alter_post_options_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Post Comment', 'verbose_name_plural': 'Post Comments'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, validators=[blog.models.validate_title]),
        ),
    ]
