version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tlearning_db
      POSTGRES_USER: t_abildayeva
      POSTGRES_PASSWORD: t_abildayeva
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./tlearning:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:

# Tamiris Abildayeva 